[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[cache]
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 3000

[context.production.environment]
  VITE_SITE_TITLE = "Kriti Chinta - Software Developer"
  VITE_SITE_DESCRIPTION = "Creating beautiful, performant web experiences"
